output * bg ~/Pictures/wallpapers/1.png fill

smart_gaps off
gaps inner 4
gaps outer 2

default_border pixel 2
default_floating_border pixel 2

for_window [title=".*"] border pixel 2

# class                 border  backgr. text    indicator child_border
client.focused          #cdd6f4 #cdd6f4 #1e1e2e #cdd6f4   #cdd6f4
client.focused_inactive #595959 #595959 #cdd6f4 #595959   #595959
client.unfocused        #595959 #595959 #cdd6f4 #595959   #595959
client.urgent           #f38ba8 #f38ba8 #11111b #f38ba8   #f38ba8

seat * xcursor_theme Bibata-Modern-Ice 22

# --- GTK Theme Enforcement ---
set $gnome-schema org.gnome.desktop.interface
exec_always gsettings set $gnome-schema color-scheme 'prefer-dark'
exec_always gsettings set $gnome-schema gtk-theme 'Adwaita-dark'
