# Volume and Brightness
bindsym XF86AudioRaiseVolume exec wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindsym XF86AudioLowerVolume exec wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindsym XF86AudioMute exec wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindsym XF86AudioMicMute exec wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindsym XF86MonBrightnessUp exec brightnessctl -e4 -n2 set 5%+
bindsym XF86MonBrightnessDown exec brightnessctl -e4 -n2 set 5%-

# Media Player
bindsym XF86AudioNext exec playerctl next
bindsym XF86AudioPause exec playerctl play-pause
bindsym XF86AudioPlay exec playerctl play-pause
bindsym XF86AudioPrev exec playerctl previous

# Core
bindsym $mod+Return exec $terminal
bindsym $mod+q kill
bindsym $mod+e exec $fileManager
bindsym $mod+c floating toggle
bindsym $mod+space exec $menu
bindsym $mod+p layout toggle split
bindsym $mod+j layout toggle split
bindsym $mod+f fullscreen toggle
bindsym $mod+l exec wlogout -b 5
bindsym $mod+Shift+c reload

# Clipboard & Screenshots
bindsym $mod+v exec $scriptsDir/cliphist.sh -c
bindsym $mod+Shift+v exec $scriptsDir/cliphist.sh -w
# 1. Fast Path: Crop -> Immediate Clipboard (No UI)
bindsym $mod+s exec sh -c 'grim -g "$(slurp)" - | wl-copy'

# 2. Edit Path: Crop -> Swappy UI (Edit, Save, Copy)
bindsym $mod+Shift+s exec $scriptsDir/satty-shot.sh

# Scripts
bindsym $mod+w exec $scriptsDir/wallpaper.sh
bindsym $mod+t exec $scriptsDir/wlsunset-toggle.sh
bindsym $mod+r exec ~/.config/waybar/scripts/launch.sh

# Navigation
bindsym $mod+Left focus left
bindsym $mod+Right focus right
bindsym $mod+Up focus up
bindsym $mod+Down focus down

# Window Movement
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Right move right
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Down move down

# Resizing
bindsym $mod+Control+Right exec $scriptsDir/sway-win-resize.sh right 25
bindsym $mod+Control+Left  exec $scriptsDir/sway-win-resize.sh left  25
bindsym $mod+Control+Up    exec $scriptsDir/sway-win-resize.sh up    25
bindsym $mod+Control+Down  exec $scriptsDir/sway-win-resize.sh down  25

# Workspaces
bindcode $mod+10 workspace number 1
bindcode $mod+11 workspace number 2
bindcode $mod+12 workspace number 3
bindcode $mod+13 workspace number 4

bindcode $mod+Shift+10 move container to workspace number 1
bindcode $mod+Shift+11 move container to workspace number 2
bindcode $mod+Shift+12 move container to workspace number 3
bindcode $mod+Shift+13 move container to workspace number 4

bindsym $mod+button5 workspace next_on_output
bindsym $mod+button4 workspace prev_on_output
