# --- Waybar Tool Popups ---
for_window [app_id="pavucontrol"] floating enable, resize set width 600 px height 450 px, move position center
for_window [app_id="nm-connection-editor"] floating enable, resize set width 600 px height 450 px, move position center
for_window [app_id="blueman-manager"] floating enable, resize set width 600 px height 450 px, move position center
for_window [app_id="satty"] floating enable, border pixel 2, resize set 1200 800, move position center
for_window [app_id="com.gabm.satty"] floating enable, border pixel 2, resize set 1200 800, move position center
