#configs path
$configs = $HOME/.config/hypr/configs

source = $configs/environment.conf

source = $configs/monitors.conf
source = $configs/workspaces.conf
source = $configs/input.conf

source = $configs/looks/misc.conf
source = $configs/looks/appearance.conf
source = $configs/looks/animations.conf
source = $configs/looks/layout.conf

source = $configs/windowrule.conf
source = $configs/keybinds.conf

# Must be last, ensures all rules and monitor settings are active 
source = $configs/autostart.conf
