# Navigation
n playlist-next
p playlist-prev
SHIFT+RIGHT playlist-next
SHIFT+LEFT playlist-prev

# Seek & Volume
RIGHT seek 10
LEFT seek -10
UP add volume 5
DOWN add volume -5

# Controls
l cycle-values loop-file "inf" "no"
s playlist-shuffle
